### ISSUE TITLE
変換後のwavファイルの音声が実際よりもゆっくり聞こえる

### ISSUE THREAD

**Issue by yossan4343434** [furuya02/AmazonConnectExtension005#1]
## ご挨拶
初めまして。都内でエンジニアをしております yossan4343434（よっさん） と申します。
Amazon connectを用いたサービスの開発を行っておりまして、こちらの記事を大変参考にさせていただいております。大変丁寧に解説してくださり、音声データに関する知見のない小生には本当に助かっております。
https://dev.classmethod.jp/articles/amazon-connect-extended-voicemail/

## 課題
こちらのリポジトリをクローンし、動作確認を行ったところ、
**S3にアップロードされた.wavファイルの音声が実際よりもゆっくりと聞こえる** という事象がみられたため、イシューとして報告させていただきます。

こちらがS3に格納された音声ファイルです。
[2020-04-23_09_55.wav.zip](https://github.com/furuya02/AmazonConnectExtension005/files/4519716/2020-04-23_09_55.wav.zip)
（「こんにちは。電話を切ります。」というメッセージを残していますが、ゆっくりと聞こえます）

## 実行手順
こちらの記事の「3 設置方法」に従っています。
https://dev.classmethod.jp/articles/amazon-connect-extended-voicemail/

## 終わりに
ご執筆から数ヶ月が経過しておりますので、Amazon connectの音声データの仕様が変わっている可能性もあるかと思います。
コードの修正がお手間でしたら、修正箇所の目星（特に`src/rawToWav/ConnectVoiceMail.ts`の`_createWav`関数の定数など？）や、参考にすべきドキュメントを教えていただけましたら幸いです。
最後までお読み頂きありがとうございます。

**Comment by furuya02** [comment]
yossan4343434 様

ご連絡ありがというございます。

誠に恐縮ですが、問い合わせフロー上の「ストリーミング開始」のブロックを開いて、
「Customer only」だけにチェックして動作を確かめてみて頂けないでしょうか。

お時間の許す際にでも、ご確認頂ければ幸いです。

クラスメソッド（株）
平内真一


2020年4月23日(木) 10:46 yossan4343434 <notifications@github.com>:

**Comment by yossan4343434** [comment]
平内 様

早速のご回答ありがとうございます。

試してみたところ、見事に意図した通りの挙動になりました！

本当にありがとうございます。

**Comment by furuya02** [comment]
ご確認ありがとうございます。
修正させて頂きます。

貴重なご連絡に感謝申し上げます。m(_._)m

クラスメソッド（株）
平内真一
